apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: autogluonkserveimagev1
spec:
  source:
    type: Git
    git:
      uri: https://github.com/red-hat-data-services/kserve-autogluon-server
      ref: dev-preview-rhoai
    contextDir: python
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: autogluon.Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: autogluonkserveimagev1:latest
  triggers:
    - type: ConfigChange