kind: ConfigMap
apiVersion: v1
metadata:
  name: llama-stack-config
data:
  config.yaml: |-
    version: 2
    image_name: rh
    apis:
      - inference
      - vector_io
      - files
    storage:
      backends:
        kv_default:
          type: kv_sqlite
          db_path: ${env.SQLITE_STORE_DIR:=empty}
        sql_default:
          type: sql_sqlite
          db_path: ${env.SQLITE_STORE_DIR:=empty}
      stores:
        metadata:
          namespace: registry
          backend: kv_default
        inference:
          table_name: inference_store
          backend: sql_default
          max_write_queue_size: 10000
          num_writers: 4
        conversations:
          table_name: openai_conversations
          backend: sql_default
        prompts:
          namespace: prompts
          backend: kv_default
    providers:
      inference:
        - model_id: ${env.LLM_MODEL_ID}
          provider_id: ${env.LLM_PROVIDER_ID}
          provider_type: remote::vllm
          model_type: llm
          metadata: {}
          config:
            base_url: ${env.LLM_MODEL_URL}
            max_tokens: ${env.LLM_MAX_TOKENS:=4096}
            api_token: ${env.LLM_MODEL_TOKEN}
            tls_verify: false
        - model_id: ${env.EMB_MODEL_ID}
          provider_id: ${env.EMB_PROVIDER_ID:=vllm-embedding}
          provider_model_id: ${env.PROVIDER_MODEL_ID}
          provider_type: remote::vllm
          model_type: embedding
          config:
            base_url: ${env.EMB_MODEL_URL}
            max_tokens: ${env.EMB_MAX_TOKENS:=512}
            api_token: ${env.EMB_MODEL_TOKEN}
            tls_verify: false
      vector_io:
      - provider_id: milvus
        provider_type: inline::milvus
        config:
          db_path: /opt/app-root/src/.llama/distributions/rh/milvus.db
          persistence:
            namespace: vector_io::milvus
            backend: kv_default
      files:
      - provider_id: meta-reference-files
        provider_type: inline::localfs
        config:
          storage_dir: /opt/app-root/src/.llama/distributions/rh/files
          metadata_store:
            backend: sql_default
            table_name: files_metadata
    registered_resources:
      models:
      - model_id: ${env.LLM_MODEL_ID}
        provider_id: ${env.LLM_PROVIDER_ID}
        model_type: llm
        metadata: {}
      - metadata:
          embedding_dimension: ${env.EMB_MODEL_DIMENSION:=768}
        model_id: ${env.EMB_MODEL_ID}
        provider_id: ${env.EMB_PROVIDER_ID:=vllm-embedding}
        provider_model_id: ${env.PROVIDER_MODEL_ID}
        model_type: embedding
    server:
      port: 8321
      auth:
        provider_config:
          type: "oauth2_token"
          jwks:
            uri: "https://keycloak-service-${env.KEYCLOAK_NS}.svc.cluster.local:8443/realms/${env.KEYCLOAK_REALM}/protocol/openid-connect/certs"
            key_recheck_period: 3600
          issuer: "https://keycloak-service-${env.KEYCLOAK_NS}.svc.cluster.local:8443/realms/${env.KEYCLOAK_REALM}"
          audience: "account"
          verify_tls: false
